name: taskell
version: '1.11.4'
category: Command Line Tools
author: Mark Wales
maintainer: mark@smallhadroncollider.com
copyright: 2019 Mark Wales
license: BSD3
synopsis: A command-line kanban board/task manager
description: Please see the README on GitHub at <https://github.com/smallhadroncollider/taskell#readme>
github: smallhadroncollider/taskell

extra-source-files:
- README.md
- templates/*
- test/Taskell/IO/data/*.json
- test/Taskell/IO/data/*.md
- test/Taskell/IO/Keyboard/data/bindings.ini

default-extensions:
- OverloadedStrings
- NoImplicitPrelude
- TupleSections
- LambdaCase
- RankNTypes

dependencies:
- classy-prelude

library:
  source-dirs: src
  exposed-modules:
  - Taskell
  - Taskell.Events.State
  - Taskell.IO.Config
  - Taskell.IO

  # tests
  - Taskell.Data.Date
  - Taskell.Data.Date.RelativeParser
  - Taskell.Data.List
  - Taskell.Data.Lists
  - Taskell.Data.Seq
  - Taskell.Data.Subtask
  - Taskell.Data.Task
  - Taskell.Events.Actions.Types
  - Taskell.Events.State.History
  - Taskell.Events.State.Types
  - Taskell.Events.State.Types.Mode
  - Taskell.IO.Config.Markdown
  - Taskell.IO.Markdown.Parser
  - Taskell.IO.Markdown.Serializer
  - Taskell.IO.HTTP.GitHub
  - Taskell.IO.HTTP.GitHub.Card
  - Taskell.IO.HTTP.Trello.List
  - Taskell.IO.HTTP.Trello.ChecklistItem
  - Taskell.IO.Keyboard
  - Taskell.IO.Keyboard.Parser
  - Taskell.IO.Keyboard.Types
  - Taskell.UI.Draw.Field
  - Taskell.Types

  dependencies:
  - base <=5
  - aeson
  - attoparsec
  - brick
  - bytestring
  - config-ini
  - containers
  - directory
  - file-embed
  - fold-debounce
  - http-conduit
  - http-client
  - http-types
  - lens
  - mtl
  - optparse-applicative
  - template-haskell
  - text
  - time
  - tz
  - vty

executables:
  taskell:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - taskell
    - tz

tests:
  taskell-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - aeson
    - containers
    - file-embed
    - lens
    - mtl
    - raw-strings-qq
    - taskell
    - tasty
    - tasty-discover
    - tasty-expected-failure
    - tasty-hunit
    - text
    - time
    - tz
    - vty
