name: taskell
version: '1.6.1.0'
category: Command Line Tools
author: Mark Wales
maintainer: mark@smallhadroncollider.com
copyright: 2019 Mark Wales
license: BSD3
synopsis: A command-line kanban board/task manager
description: Please see the README on GitHub at <https://github.com/smallhadroncollider/taskell#readme>
github: smallhadroncollider/taskell

extra-source-files:
- README.md
- templates/*

default-extensions:
- OverloadedStrings
- NoImplicitPrelude

dependencies:
- classy-prelude

library:
  source-dirs: src
  exposed-modules:
  - App
  - Events.State
  - IO.Config
  - IO.Taskell

  # tests
  - Data.Taskell.Date
  - Data.Taskell.List
  - Data.Taskell.List.Internal
  - Data.Taskell.Lists
  - Data.Taskell.Lists.Internal
  - Data.Taskell.Seq
  - Data.Taskell.Subtask
  - Data.Taskell.Subtask.Internal
  - Data.Taskell.Task
  - Data.Taskell.Task.Internal
  - Events.Actions.Types
  - Events.State.Types
  - Events.State.Types.Mode
  - IO.Config.Markdown
  - IO.Markdown.Internal
  - IO.HTTP.GitHub
  - IO.HTTP.Trello.List
  - IO.HTTP.Trello.ChecklistItem
  - IO.Keyboard
  - IO.Keyboard.Parser
  - IO.Keyboard.Types
  - UI.Draw.Field
  - Types

  dependencies:
  - base <=5
  - aeson
  - attoparsec
  - brick
  - bytestring
  - config-ini
  - containers
  - directory
  - file-embed
  - fold-debounce
  - http-conduit
  - http-client
  - http-types
  - lens
  - mtl
  - template-haskell
  - text
  - time
  - vty

executables:
  taskell:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - taskell

tests:
  taskell-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - aeson
    - containers
    - file-embed
    - lens
    - raw-strings-qq
    - taskell
    - tasty
    - tasty-discover
    - tasty-expected-failure
    - tasty-hunit
    - text
    - time
    - vty
