set :deploy_config_path, 'deployment/deploy.rb'
set :stage_config_path, 'deployment/deploy'

# Load DSL and set up stages
require 'capistrano/setup'

# Include default deployment tasks
require 'capistrano/deploy'
require 'capistrano/console'

# Git
require "capistrano/scm/git"
install_plugin Capistrano::SCM::Git
